apiVersion: v1
kind: Secret
metadata:
  name: nexus-repository-secret
data:
  # Nexus private Docker repository
  .dockerconfigjson: andkfjnKJHKweffdasLKJOJI
type: kubernetes.io/dockerconfigjson

# {
#         "auths": {
#                 "nexus.example.com": {
#                         "auth": "asdf^%$^(&*JHGIKBNJ"
#                 }
#         },
#         "HttpHeaders": {
#                 "User-Agent": "Docker-Client/18.05.0-ce (linux)"
#         }
# }
#
# # # Below command to get .dockerconfigjson in base64 format
# cat ~/.docker/config.json | base64