---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
    tier: frontend
  ports:
  - protocol: "TCP"
    name: http
    port: 9080
    targetPort: 80
  - protocol: "TCP"
    name: https
    port: 9443
    targetPort: 443
  type: LoadBalancer